<?php

		require_once "Sql.php";

		$sql = new Sql();

		// EXECUÇÃO DE UM INSERT USANDO A FUNÇÃO QUERY
		// NO PRIMEIRO PARAMETRO VAI A CONSULTA EM FORMA DE STRING
		// NO SEGUNDO PARAMETRO VAI O ARRAY COM AS CHAVES E OS DADOS QUE SERÃO ATRIBUÍDOS AOS ELEMENTOS DA CONSULTA
		$sql->query("INSERT INTO TESTE VALUES(:ID, :NOME, :IDADE)", [":ID"=>'DEFAULT', ":NOME"=>'Beutrano De Oliveira', ":IDADE"=>49]);

		// EXECUÇÃO DE UM SELECT USANDO A FUNÇÃO SELECT
		// NO PRIMEIRO PARAMETRO VAI A CONSULTA EM FORMA DE STRING
		// NO SEGUNDO PARAMETRO VAI O ARRAY COM AS CHAVES E OS DADOS QUE SERÃO ATRIBUÍDOS AOS ELEMENTOS DA CONSULTA
		// COMO SE TRATA DE UM SELECT A CONSULTA RETORNARA OS DADOS EM FORMA DE ARRAY, ENTÃO É NECESSÁRIO ARMAZENAR EM UMA VARIÁVEL
		$results = $sql->select("SELECT * FROM TESTE WHERE IDADE > :IDADE", [":IDADE"=>19]);

		// EXECUÇÃO DE UM INSERT USANDO A FUNÇÃO QUERY
		$sql->query("DELETE FROM TESTE WHERE ID = :ID", [":ID"=>25]);

		// EXECUÇÃO DE UM INSERT USANDO A FUNÇÃO QUERY
		$sql->query("UPDATE TESTE SET NAME = :NOME WHERE ID = :ID", [":NOME"=>"Outro Nome", ":ID"=>24]);

		